name: "Python Code Style Action"
description: "This action helps python code to adhere to the celebrate coding standards."
inputs:
  github_token:
    description: ""
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Check reporter type
      id: reporter-check
      shell: bash
      run: |
        if [ ${{ github.event_name }} = "pull_request" ]; then
            echo "::set-output name=reporter::github-pr-review"
        else
            echo "::set-output name=reporter::github-check"
        fi

    - name: Detect changed files
      uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          addedOrModifiedPython:
            - added|modified: '**/*.py'
        list-files: shell

    - name: flake8
      uses: reviewdog/action-flake8@v3
      with:
        flake8_args: ${{ steps.changes.outputs.addedOrModifiedPython_files }}
        reporter: ${{ steps.reporter-check.outputs.reporter }}

    - name: mypy
      uses: tsuyoshicho/action-mypy@v3.11.0
      with:
        target: ${{ steps.changes.outputs.addedOrModifiedPython }}
        reporter: ${{ steps.reporter-check.outputs.reporter }}

    - name: pylint
      uses: dciborow/action-pylint@0.1.0
      with:
        glob_pattern: ${{ steps.changes.outputs.addedOrModifiedPython_files }}
        reporter: ${{ steps.reporter-check.outputs.reporter }}
